version: '3.8'

services:
  model_service:
    build:
      context: service_model
      dockerfile: Dockerfile
    container_name: model_service
    ports:
      - "8000:8000"
    networks:
      - app_network

  gradio_service:
    build:
      context: service_gradio
      dockerfile: Dockerfile
    container_name: gradio_service
    ports:
      - "7860:7860"
    networks:
      - app_network
    depends_on:
      - model_service

networks:
  app_network:
    driver: bridge